// <auto-generated />
namespace ThuongMaiDienTu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TMDT4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TMDT4));
        
        string IMigrationMetadata.Id
        {
            get { return "201912231041014_TMDT4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
